import random
from typing import Optional

from flask_classful import route, FlaskView

from Api import UserApi, RecipeApi, RecipeBookApi
from Database import DatabaseConstants, Models
from Database.Models.Recipe import RecipeStep, RecipeIngredient, RecipeStepLength


class DevRoute(FlaskView):
    @route('/init', methods=['GET'])
    def initData(self):
        user = self._createUser()
        recipes = self._createRecipes(user)
        self._createRecipeBooks(user, recipes)
        return 'OK', 200

    def _createUser(self) -> Models.User:
        user = UserApi.UserApi.create(username='test@asdf.qwer', password='asdfqwer')
        user['_id'] = str(user['_id'])
        return user

    def _createRecipeBooks(self, user: Models.User, recipes: [Models.Recipe]) -> [Models.RecipeBook]:
        books = []

        def rollRecipes() -> [str]:
            chosenRecipes = random.choices(recipes, k=random.randint(0, DatabaseConstants.PAGE_SIZE + 2))
            return [r['_id'] for r in chosenRecipes]

        for i in range(0, DatabaseConstants.PAGE_SIZE + 20):
            books.append(RecipeBookApi.RecipeBookApi.create(
                Models.RecipeBook(
                    name=f'Test Book {i}',
                    description='A test recipe book, generated by dev routes',
                    recipes=rollRecipes(),
                    owner=user['_id']
                ), user['_id'])
            )
        return books

    def _createRecipes(self, user: Models.User) -> [Models.Recipe]:
        createdRecipes = []
        for i in range(0, DatabaseConstants.PAGE_SIZE + 20):
            createdRecipes.append(RecipeApi.RecipeApi.create(
                Models.Recipe(
                    name=f'Test Recipe {i}',
                    description=f'A test recipe that has the number {i}',
                    owner=user['_id'],
                    private=(i % 2 == 0),
                    steps=self._createSteps(),
                    ingredients=self._createIngredients(),
                    advanced={},
                    links=[],
                ), user['_id'])
            )
        return createdRecipes

    def _createSteps(self) -> [RecipeStep]:
        def rollUnit() -> str:
            units = ['m', 'h', 'd', 'w']
            return random.choice(units)

        def rollTime() -> int:
            return random.randint(10, 100)

        def genLen() -> Optional[RecipeStepLength]:
            return {'time': rollTime(), 'unit': rollUnit()}

        numSteps = random.randint(1, 20)
        steps = []
        for i in range(0, numSteps):
            steps.append(RecipeStep(
                content=f'This is a step with the index of number {i}.',
                length=genLen()
            ))
        return steps

    def _createIngredients(self) -> [RecipeIngredient]:
        numIngs = random.randint(1, 20)
        ings = []
        for i in range(0, numIngs):
            ings.append(RecipeIngredient(name=f'Ing {i}', amount='3/14', unit='asdf'))
        return ings
