version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: 'recipiece-db'
    volumes:
      - ./mongo.js:/docker-entrypoint-initdb.d/mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: recipiece
      MONGO_INITDB_ROOT_PASSWORD: test1234
      MONGO_INITDB_DATABASE: recipiece
    ports:
      - 27017:27017
  test_mongo:
    image: mongo:latest
    container_name: 'recipiece-test-db'
    volumes:
      - ./mongo.js:/docker-entrypoint-initdb.d/mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: recipiece
      MONGO_INITDB_ROOT_PASSWORD: test1234
      MONGO_INITDB_DATABASE: recipiece
    ports:
      - 27018:27017