version: '3'
services:
  recipiece_database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'recipiece'
      MYSQL_USER: 'recipiece'
      MYSQL_PASSWORD: 'test1234'
      MYSQL_ROOT_PASSWORD: 'test1234'
    volumes:
      - ./DOCKER_INIT.sql:/docker-entrypoint-initdb.d/DOCKER_INIT.sql
  recipiece_test_database:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'recipiece'
      MYSQL_USER: 'recipiece'
      MYSQL_PASSWORD: 'test1234'
      MYSQL_ROOT_PASSWORD: 'test1234'
    volumes:
      - ./DOCKER_INIT.sql:/docker-entrypoint-initdb.d/DOCKER_INIT.sql